# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-helloworld-pro-sailfish

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Helloworld Pro for Sailfish
Version:    0.5
Release:    5
Group:      Qt/Qt
License:    Public domain except for the icon
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-helloworld-pro-sailfish.yaml
Requires:   libsailfishapp
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  desktop-file-utils

%description
Missing Helloworld for Sailfish OS. Use this project for a good app start

%package test
Summary:    Tests for the Helloworld Pro for Sailfish
Group:      Qt/Qt
Requires:   %{name} = %{version}-%{release}
Requires:   qt5-qtdeclarative-import-qttest
BuildRequires:  pkgconfig(Qt5QuickTest)

%description test
Tests package for the Helloworld Pro for Sailfish

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(0644,root,root,0755)
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/applications/%{name}.desktop
%{_datadir}/%{name}/qml
%attr(0755,-,-) %{_bindir}/%{name}
# >> files
# << files

%files test
%defattr(-,root,root,-)
%{_bindir}/tst-harbour-helloworld-pro-sailfish
%{_datadir}/tst-harbour-helloworld-pro-sailfish/*.qml
%{_datadir}/tst-harbour-helloworld-pro-sailfish/*.sh
%attr(0755,-,-) %{_datadir}/tst-harbour-helloworld-pro-sailfish/*.sh
# >> files test
# << files test
