# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfish-app-with-qml-test

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Sample Sailfish QML app with a test
Version:    1.0
Release:    1
Group:      Qt/Qt
License:    Public domain (unlicense)
Source0:    %{name}-%{version}.tar.bz2
Requires:   mapplauncherd-booster-silica-qt5
Requires:   sailfishsilica-qt5
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(qdeclarative5-boostable)

%description
Simple app to demonstrate an example of project and RPM structure for a simple pure QML app and a corresponding QtQuick test tes. Same approach can be used for C++ parts too though.

%package tests
Summary:    tests for the sailfish-app-with-qml-test
BuildRequires:  pkgconfig(Qt5QuickTest)
Requires:   qt5-qtdeclarative-qtquicktest
Requires:   sailfish-app-with-qml-test
Requires:   qt5-qtdeclarative-import-qttest

%description tests
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/usr/bin/sailfish-app-with-qml-test
/usr/share/sailfish-app-with-qml-test
/usr/share/applications

# tests to be located side by side to the main package and start from "tst-".
# I find it convenient. Also easy to find and remove tst- directories manually if needed
%files tests
%defattr(-,root,root,-)
/usr/bin/tst-sailfish-app-with-qml-test
/usr/share/tst-sailfish-app-with-qml-test

# >> files
# << files
